name: Update Warrant Canary

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  canary:
    runs-on: ubuntu-latest

    env:
      GPG_KEY_B64: ${{ secrets.PGP_PRIVATE_KEY_B64 }}
      GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Import GPG key
        run: |
          echo "$GPG_KEY_B64" | base64 -d > private.key
          gpg --batch --yes --import private.key

      - name: Enable GPG loopback
        run: |
          mkdir -p ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          gpgconf --kill gpg-agent
          gpgconf --launch gpg-agent

      - name: Generate and sign canary
        run: python generate_canary.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/canary.json
          git commit -m "Automated canary update"
          git push
